# common properties
server:
  port: 8080

spring:
  mvc:
    view:
      suffix: .html
  devtools:
    livereload:
      enabled: true
  thymeleaf:
    cache: false


---
# local profile
spring:
  profiles: local
api:
  end-points: http://localhost:3030


---
# local profile
spring:
  profiles: dev
api:
  end-points: http://121.141.157.230:51040
