# Common properties


---
# local profile
spring:
  profiles: local

server:
  port: 3030

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG

---
# dev profile
spring:
  profiles: dev

server:
  port: 13030
