# Common properties
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true
        enable_lazy_load_no_trans: true

batch:
  txSync:
    enable: true
    initDelay: 5000
    period: 5000


---
# local profile
spring:
  profiles: local
  datasource:
    url: jdbc:mariadb://localhost:3306/whitepin
    username: whitepin
    password: whitepin12345
    initialization-mode: always
    data: classpath:data.sql
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        generate_statistics: false
        show_sql: true
        use_sql_comments: true

server:
  port: 3030

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    com.github.whitepin.server.api.controller: DEBUG

fabric:
  caName: ca.whitepin.com
  caLocation: http://192.168.7.30:7054
  userName: Admin@Whitepin
  userPassword: WhitepinPWD
  orgMsp: WhitepinMSP
  ordererName: orderer0.whitepin.com
  ordererLocation: grpc://192.168.7.30:7050
  peerName1: peer0.whitepin.com
  peerLocation1: grpc://192.168.7.30:7051
  channelName: whitepin-main-channel

---
# dev profile
spring:
  profiles: dev
  datasource:
    url: jdbc:mariadb://192.168.7.30:3306/whitepin
    username: whitepin
    password: whitepin1234
    initialization-mode: always
    data: classpath:data.sql
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        generate_statistics: false
        show_sql: true
        use_sql_comments: true

server:
  port: 3030

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    com.github.whitepin.server.api.controller: DEBUG

fabric:
  caName: ca.whitepin.com
  caLocation: http://192.168.7.30:7054
  userName: Admin@Whitepin
  userPassword: WhitepinPWD
  orgMsp: WhitepinMSP
  ordererName: orderer0.whitepin.com
  ordererLocation: grpc://192.168.7.30:7050
  peerName1: peer0.whitepin.com
  peerLocation1: grpc://192.168.7.30:7051
  channelName: whitepin-main-channel
